export const ErrorCode = {
  AUTH_INVALID_INPUT: 'auth.invalid_input',
  AUTH_EMAIL_ALREADY_REGISTERED: 'auth.email_already_registered',
  AUTH_INVALID_CREDENTIALS: 'auth.invalid_credentials',
  AUTH_REGISTRATION_UNAVAILABLE: 'auth.registration_unavailable',
  AUTH_SESSION_UNAVAILABLE: 'auth.session_unavailable',
  AUTH_SIGN_OUT_UNAVAILABLE: 'auth.sign_out_unavailable',
  ACCESS_DENIED: 'access.denied',
  ACCESS_MEMBERSHIP_REQUIRED: 'access.membership_required',
  ACCESS_INVALID_ROLE: 'access.invalid_role',
  ACCESS_ROLE_NAME_CONFLICT: 'access.role_name_conflict',
  ACCESS_ROLE_UNAVAILABLE: 'access.role_unavailable',
  ACCESS_TARGET_UNAVAILABLE: 'access.target_unavailable',
  ACCESS_PROTECTED_ROLE: 'access.protected_role',
  ACCESS_MANAGER_TRANSFER_REQUIRED: 'access.manager_transfer_required',
  ACCESS_REPLACEMENT_REQUIRED: 'access.replacement_required',
  ACCESS_INVALID_MANAGER_TRANSFER: 'access.invalid_manager_transfer',
  ACCESS_CONCURRENT_CHANGE: 'access.concurrent_change',
  ACCESS_ROLE_DELETION_UNAVAILABLE: 'access.role_deletion_unavailable',
  ACCESS_MANAGER_TRANSFER_UNAVAILABLE: 'access.manager_transfer_unavailable',
  USERS_SELF_ACTION_FORBIDDEN: 'users.self_action_forbidden',
  USERS_PROTECTED_MANAGER_TARGET: 'users.protected_manager_target',
  USERS_PERMISSION_EXCEEDED_TARGET: 'users.permission_exceeded_target',
  USERS_RESERVED_ROLE_SELECTION: 'users.reserved_role_selection',
  INTERNAL_ERROR: 'system.internal_error',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
