export const ErrorCode = {
  AUTH_INVALID_INPUT: 'auth.invalid_input',
  AUTH_EMAIL_ALREADY_REGISTERED: 'auth.email_already_registered',
  AUTH_INVALID_CREDENTIALS: 'auth.invalid_credentials',
  AUTH_REGISTRATION_UNAVAILABLE: 'auth.registration_unavailable',
  AUTH_SESSION_UNAVAILABLE: 'auth.session_unavailable',
  AUTH_SIGN_OUT_UNAVAILABLE: 'auth.sign_out_unavailable',
  ACCESS_DENIED: 'access.denied',
  ACCESS_MEMBERSHIP_REQUIRED: 'access.membership_required',
  ACCESS_INVALID_ROLE: 'access.invalid_role',
  ACCESS_ROLE_NAME_CONFLICT: 'access.role_name_conflict',
  ACCESS_ROLE_UNAVAILABLE: 'access.role_unavailable',
  ACCESS_TARGET_UNAVAILABLE: 'access.target_unavailable',
  ACCESS_PROTECTED_ROLE: 'access.protected_role',
  ACCESS_MANAGER_TRANSFER_REQUIRED: 'access.manager_transfer_required',
  ACCESS_REPLACEMENT_REQUIRED: 'access.replacement_required',
  ACCESS_INVALID_MANAGER_TRANSFER: 'access.invalid_manager_transfer',
  ACCESS_CONCURRENT_CHANGE: 'access.concurrent_change',
  ACCESS_ROLE_DELETION_UNAVAILABLE: 'access.role_deletion_unavailable',
  ACCESS_MANAGER_TRANSFER_UNAVAILABLE: 'access.manager_transfer_unavailable',
  USERS_SELF_ACTION_DENIED: 'users.self_action_denied',
  USERS_MANAGER_ROLE_PROTECTED: 'users.manager_role_protected',
  USERS_PERMISSION_EXCEEDED: 'users.permission_exceeded',
  USERS_RESERVED_ROLE_SELECTION: 'users.reserved_role_selection',
  USERS_CREATION_UNAVAILABLE: 'users.creation_unavailable',
  USERS_PASSWORD_CHANGE_UNAVAILABLE: 'users.password_change_unavailable',
  USERS_DELETION_UNAVAILABLE: 'users.deletion_unavailable',
  INTERNAL_ERROR: 'system.internal_error',
  WORKSPACE_DENIED: 'workspace.denied',
  WORKSPACE_INVALID_INPUT: 'workspace.invalid_input',
  WORKSPACE_TARGET_UNAVAILABLE: 'workspace.target_unavailable',
  WORKSPACE_ROLE_NAME_CONFLICT: 'workspace.role_name_conflict',
  WORKSPACE_PROTECTED_ROLE: 'workspace.protected_role',
  WORKSPACE_SYSTEM_MANAGED_PERMISSION: 'workspace.system_managed_permission',
  WORKSPACE_OWNER_TRANSFER_REQUIRED: 'workspace.owner_transfer_required',
  WORKSPACE_ROLE_ASSIGNMENT_REQUIRED: 'workspace.role_assignment_required',
  WORKSPACE_REPLACEMENT_ROLE_REQUIRED: 'workspace.replacement_role_required',
  WORKSPACE_MEMBER_EXISTS: 'workspace.member_exists',
  WORKSPACE_WAREHOUSE_MEMBERSHIP_REQUIRED:
    'workspace.warehouse_membership_required',
  WORKSPACE_SELF_ACTION_DENIED: 'workspace.self_action_denied',
  WORKSPACE_MANAGER_TRANSFER_REQUIRED: 'workspace.manager_transfer_required',
  WORKSPACE_MEMBERSHIP_EXISTS: 'workspace.membership_exists',
  WORKSPACE_WAREHOUSE_ARCHIVED: 'workspace.warehouse_archived',
  WORKSPACE_LAST_UNARCHIVED_WAREHOUSE: 'workspace.last_unarchived_warehouse',
  WORKSPACE_CONCURRENT_CHANGE: 'workspace.concurrent_change',
  ACCESS_WAREHOUSE_ARCHIVED: 'access.warehouse_archived',
  WORKSPACE_WAREHOUSE_CREATION_UNAVAILABLE:
    'workspace.warehouse_creation_unavailable',
  WORKSPACE_ARCHIVAL_UNAVAILABLE: 'workspace.archival_unavailable',
  WORKSPACE_ROLE_DELETION_UNAVAILABLE: 'workspace.role_deletion_unavailable',
  WORKSPACE_OWNER_TRANSFER_UNAVAILABLE: 'workspace.owner_transfer_unavailable',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
