export const PermissionId = {
  USERS_CREATE: 'USERS:CREATE',
  USERS_UPDATE: 'USERS:UPDATE',
  USERS_WATCH: 'USERS:WATCH',
  ROLES_ASSIGN: 'ROLES:ASSIGN',
  ROLES_CREATE: 'ROLES:CREATE',
  ROLES_UPDATE: 'ROLES:UPDATE',
  ROLES_DELETE: 'ROLES:DELETE',
  ROLES_WATCH: 'ROLES:WATCH',
  WAREHOUSE_MANAGER_ROLE_REASSIGN: 'WAREHOUSE_MANAGER_ROLE:REASSIGN',
  USERS_EMAIL_UPDATE: 'USERS:EMAIL_UPDATE',
  USERS_PASSWORD_CHANGE: 'USERS:PASSWORD_CHANGE',
  USERS_DELETE: 'USERS:DELETE',
} as const;

export type PermissionId = (typeof PermissionId)[keyof typeof PermissionId];
