export const WorkspacePermissionId = {
  WORKSPACE_RENAME: 'WORKSPACE:RENAME',
  WORKSPACE_ROLES_WATCH: 'WORKSPACE_ROLES:WATCH',
  WORKSPACE_ROLES_CREATE: 'WORKSPACE_ROLES:CREATE',
  WORKSPACE_ROLES_UPDATE: 'WORKSPACE_ROLES:UPDATE',
  WORKSPACE_ROLES_DELETE: 'WORKSPACE_ROLES:DELETE',
  WORKSPACE_ROLES_ASSIGN: 'WORKSPACE_ROLES:ASSIGN',
  WORKSPACE_MEMBERS_WATCH: 'WORKSPACE_MEMBERS:WATCH',
  WORKSPACE_MEMBERS_ADD: 'WORKSPACE_MEMBERS:ADD',
  WORKSPACE_MEMBERS_REMOVE: 'WORKSPACE_MEMBERS:REMOVE',
  WAREHOUSES_WATCH: 'WAREHOUSES:WATCH',
  WAREHOUSES_CREATE: 'WAREHOUSES:CREATE',
  WAREHOUSES_RENAME: 'WAREHOUSES:RENAME',
  WAREHOUSES_ARCHIVE: 'WAREHOUSES:ARCHIVE',
  WAREHOUSE_MEMBERSHIPS_ASSIGN: 'WAREHOUSE_MEMBERSHIPS:ASSIGN',
  WAREHOUSE_MEMBERSHIPS_REVOKE: 'WAREHOUSE_MEMBERSHIPS:REVOKE',
  WORKSPACE_OWNER_ROLE_REASSIGN: 'WORKSPACE_OWNER_ROLE:REASSIGN',
} as const;

export type WorkspacePermissionId =
  (typeof WorkspacePermissionId)[keyof typeof WorkspacePermissionId];
